config/routes.rb
Rails.application.routes.draw do
  get 'dishes/index'

  get 'dishes/show'

  get 'dishes/new'

  get 'dishes/edit'

  root 'dishes#index'
  get 'dishes/index'
  resources :courses
  resources :dishes

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :dishes
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  def index
    @courses = Course.all
  end

  # GET /dishes/1
  def show
    redirect_to dishes_path
  end

  # GET /dishes/new
  def new
    @dish = Dish.new(course_id: params[:course_id])
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      redirect_to @dish, notice: 'Dish was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dishes/1
  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Dish was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /dishes/1
  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: 'Dish was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dish_params
      params.require(:dish).permit(:price, :name, :description, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<button><%= link_to 'Show', @dish %></button>
<button><%= link_to 'Back', dishes_path %></button>
<button><%= link_to 'Destroy', @dish, method: :delete, data: { confirm: 'Are you sure?' } %></button>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<div>
<h1 class="menu">Menu</h1>

<% @courses.each do |course| %>
  <% if course.id == 1 %>
    <%= image_tag asset_url("appetizer-logo.png"), class: "appetizer-image" %>
  <% elsif course.id == 2 %>
    <%= image_tag asset_url("entree.png"), class: "entree-image" %>
  <% else course.id == 3 %>
    <%= image_tag asset_url("dessert.jpg"), class: "dessert-image" %>
  <% end %>

  <!-- <h2><%= course.name %></h2> -->

  <% course.dishes.each do |dish| %>
    <div class="menu-blocks">
      <br>
      <p class="dish-name"><%= link_to "#{dish.name}", edit_dish_path(dish) %> <span id="price">$<%= dish.price %></span></p>
      <p class="menu-item"><%= dish.description %></p>
    </div>
  <% end %>
  <div class="addto-block"
    <p><%= link_to "Add to #{course.name}", new_dish_path(course_id: course.id)%></p>
  </div>
<% end %>
</div>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> 
<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>